version: '3.8'
services:
  db:
    image: postgis/postgis:14-3.3
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
      ML_API_URL: http://ml-api:8000

  ml-api:
    build:
      context: ../tarang-backend-ml # Path relative to this docker-compose file
    ports:
      - "8000:8000"

volumes:
  db_data: